---

- name: Master | Main BIND config file (master)
  template:
    src: master_etc_named.conf.j2
    dest: "{{ bind_config }}"
    owner: "{{ bind_owner }}"
    group: "{{ bind_group }}"
    mode: '0640'
    setype: named_conf_t
    validate: 'named-checkconf %s'
  notify: Restart named

- name: Master | Create forward lookup zone file for external view
  template:
    src: bind_zone_external.j2
    dest: "{{ bind_zone_dir_external }}/{{ item.name }}"
    owner: "{{ bind_owner }}"
    group: "{{ bind_group }}"
    mode: "{{ bind_zone_file_mode }}"
    setype: named_zone_t
    validate: 'named-checkzone -d {{ item.name }} %s'
  with_items:
    - "{{ bind_zone_domains + bind_zone_domains_external }}"
  notify: Restart named

- name: Master | Create forward lookup zone file for internal view
  template:
    src: bind_zone_internal.j2
    dest: "{{ bind_zone_dir_internal }}/{{ item.name }}"
    owner: "{{ bind_owner }}"
    group: "{{ bind_group }}"
    mode: "{{ bind_zone_file_mode }}"
    setype: named_zone_t
    validate: 'named-checkzone -d {{ item.name }} %s'
  with_items:
    - "{{ bind_zone_domains + bind_zone_domains_internal }}"
  notify: Restart named

- name: Master | Create reverse lookup zone file for external view
  template:
    src: reverse_zone_external.j2
    dest: "{{ bind_zone_dir_external }}/{{ ('.'.join(item.1.replace(item.1+'.','').split('.')[::-1])) }}.in-addr.arpa"
    owner: "{{ bind_owner }}"
    group: "{{ bind_group }}"
    mode: "{{ bind_zone_file_mode }}"
    setype: named_zone_t
    validate: "named-checkzone {{ ('.'.join(item.1.replace(item.1+'.','').split('.')[::-1])) }}.in-addr.arpa %s"
  with_subelements:
    - "{{ bind_zone_domains + bind_zone_domains_external }}"
    - networks
    - flags:
      skip_missing: true
  notify: Restart named

- name: Master | Create reverse lookup zone file for internal view
  template:
    src: reverse_zone_internal.j2
    dest: "{{ bind_zone_dir_internal }}/{{ ('.'.join(item.1.replace(item.1+'.','').split('.')[::-1])) }}.in-addr.arpa"
    owner: "{{ bind_owner }}"
    group: "{{ bind_group }}"
    mode: "{{ bind_zone_file_mode }}"
    setype: named_zone_t
    validate: "named-checkzone {{ ('.'.join(item.1.replace(item.1+'.','').split('.')[::-1])) }}.in-addr.arpa %s"
  with_subelements:
    - "{{ bind_zone_domains + bind_zone_domains_internal }}"
    - networks
    - flags:
      skip_missing: true
  notify: Restart named

- name: Master | Create reverse IPv6 lookup zone file for external view
  template:
    src: reverse_zone_ipv6.j2
    dest: "{{bind_zone_dir_external}}/{{ (item.1 | ipaddr('revdns'))[-(9+(item.1|regex_replace('^.*/','')|int)//2):-1] }}"
    owner: "{{ bind_owner }}"
    group: "{{ bind_group }}"
    mode: "{{ bind_zone_file_mode }}"
    setype: named_zone_t
    validate: "named-checkzone {{ (item.1 | ipaddr('revdns'))[-(9+(item.1|regex_replace('^.*/','')|int)//2):] }} %s"
  with_subelements:
    - "{{ bind_zone_domains + bind_zone_domains_external }}"
    - ipv6_networks
    - flags:
      skip_missing: true
  notify: Restart named

- name: Master | Create reverse IPv6 lookup zone file for internal view
  template:
    src: reverse_zone_ipv6.j2
    dest: "{{bind_zone_dir_internal}}/{{ (item.1 | ipaddr('revdns'))[-(9+(item.1|regex_replace('^.*/','')|int)//2):-1] }}"
    owner: "{{ bind_owner }}"
    group: "{{ bind_group }}"
    mode: "{{ bind_zone_file_mode }}"
    setype: named_zone_t
    validate: "named-checkzone {{ (item.1 | ipaddr('revdns'))[-(9+(item.1|regex_replace('^.*/','')|int)//2):] }} %s"
  with_subelements:
    - "{{ bind_zone_domains + bind_zone_domains_internal }}"
    - ipv6_networks
    - flags:
      skip_missing: true
  notify: Restart named

