---

- name: Master | Main BIND config file (master)
  template:
    src: master_etc_named.conf.j2
    dest: "{{ bind_config }}"
    owner: "{{ bind_owner }}"
    group: "{{ bind_group }}"
    mode: '0640'
    setype: named_conf_t
    validate: 'named-checkconf -d %s'
  notify: Restart named
  tags: always

- name: Master | Create forward lookup zone file for external view
  template:
    src: bind_zone_external.j2
    dest: "{{ bind_zone_dir_external }}/{{ item.name }}"
    owner: "{{ bind_owner }}"
    group: "{{ bind_group }}"
    mode: "{{ bind_zone_file_mode }}"
    setype: named_zone_t
    validate: 'named-checkzone -d {{ item.name }} %s'
  with_items:
    - "{{ bind_zone_domains + bind_zone_domains_external }}"
  notify: Restart named
  tags: forward

- name: Master | Create forward lookup zone file for internal view
  template:
    src: bind_zone_internal.j2
    dest: "{{ bind_zone_dir_internal }}/{{ item.name }}"
    owner: "{{ bind_owner }}"
    group: "{{ bind_group }}"
    mode: "{{ bind_zone_file_mode }}"
    setype: named_zone_t
    validate: 'named-checkzone -d {{ item.name }} %s'
  with_items:
    - "{{ bind_zone_domains + bind_zone_domains_internal }}"
  notify: Restart named
  tags: forward

- name: Master | Merge zones into one domain to build a set of reverse zones
  set_fact:
    bind_reverse_external: "{{ (bind_zone_domains + bind_zone_domains_external) | merge_zones }}"
    bind_reverse_internal: "{{ (bind_zone_domains + bind_zone_domains_internal) | merge_zones }}"
  tags: reverse

- name: Master | Create reverse lookup zone file for external view
  template:
    src: reverse_zone_external.j2
    dest: "{{ bind_zone_dir_external }}/{{ item.1 | flip_octets }}.in-addr.arpa"
    owner: "{{ bind_owner }}"
    group: "{{ bind_group }}"
    mode: "{{ bind_zone_file_mode }}"
    setype: named_zone_t
    validate: "named-checkzone {{ item.1 | flip_octets }}.in-addr.arpa %s"
  with_subelements:
    - "{{ bind_reverse_external }}"
    - networks
    - flags:
      skip_missing: true
  notify: Restart named
  tags: reverse

- name: Master | Create reverse lookup zone file for internal view
  template:
    src: reverse_zone_internal.j2
    dest: "{{ bind_zone_dir_internal }}/{{ item.1 | flip_octets }}.in-addr.arpa"
    owner: "{{ bind_owner }}"
    group: "{{ bind_group }}"
    mode: "{{ bind_zone_file_mode }}"
    setype: named_zone_t
    validate: "named-checkzone {{ item.1 | flip_octets }}.in-addr.arpa %s"
  with_subelements:
    - "{{ bind_reverse_internal }}"
    - networks
    - flags:
      skip_missing: true
  notify: Restart named
  tags: reverse
